version: '3.5'
services:
  azure-labs:
    volumes:
      - .:/usr/app/azurelabs
    image: azure-labs:latest
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure-labs
    restart: always
