version: '3.5'
services:
  azure-labs-arm64:
    volumes:
      - .:/usr/app/azurelabs
    image: azure-labs:arm64
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.amd64
    container_name: azure-labs
    restart: always
